# Configurações globais
defaults:
  timeZone: America/Sao_Paulo
  runtimeVersion: V8

# Configurações dos projetos
projects:
  salario:
    dependencies:
      userSymbol: Drive
      version: v3
      serviceId: drive
    sheetsMacros:
      - menuName: 1. VIRAR MÊS SALARIO E CONSUMO
        functionName: virarMesTudo
      - menuName: 2. VIRAR MÊS SALARIO
        functionName: virarMesSalario
      - menuName: 3. VIRAR ANO SALARIO E CONSUMO
        functionName: virarAnoTudo
      - menuName: 4. VIRAR ANO SALARIO
        functionName: virarAnoSalario
      - menuName: 5. REORDENAR NOMES
        functionName: reordenarNomes
      - menuName: LIMPAR CORES
        functionName: limparCores
      - menuName: LIMPAR DADOS
        functionName: limparDados
      - menuName: BLOQUEAR ALTERAÇÕES
        functionName: bloquearAlteracoes
    test:
      name: Macros Salários _test
      scriptId: 1ni6ZUXl1lqfBRik93jEyMI_K7-nWJBGwHPIVAb5Fw-IHZTF1UPfEiBIL
      spreadSheetId: 1n1ypLBl5fPO4eClA9uIWUvlwwYTuu2lHAwQBmaFdSkI
  
  consumo:
    dependencies:
      userSymbol: Drive
      version: v3
      serviceId: drive
    sheetsMacros:
      - menuName: 1. VIRAR MÊS CONSUMO
        functionName: virarMesConsumo
      - menuName: 2. VIRAR ANO CONSUMO
        functionName: virarAnoConsumo
    test:
      1-cafeteria:
        name: Macros Cafeteria _test
        scriptId: 1950SgMmrmWZw6clxlsFZlU6TmBnwRdahBh7entPoVAteqFta_iNNZMy-
        spreadSheetId: 15mSmurGhqrG6o1t4vr2aLPOHN2HJ_Y6SK3od-2v0CbI
      2-saara:
        name: Macros Saara _test
        scriptId: 1j2qOwS6Iehduk1IqwckujJmX-nV9AIiOU0yik-f4ja5oIcXHQNnsZMSJ
        spreadSheetId: 1o0SdfBj15wgp4VB3ajwrrChwiU6cq2NEgkBsTjFZAmk
      3-castelo:
        name: Macros Castelo _test
        scriptId: 1weezYUwBRbpriYYtaAetmkUdPQcNJUz_Q8G1e3qoZmH5UdRMK5m0c4Yh
        spreadSheetId: 1tCBoBkFnbjwHKiCN6TiLpwO_X9Z0Z7WKd9y7cz_2yIM
      4-stones:
        name: Macros Stones _test
        scriptId: 1x-UClZ5PEuUYbwrcM2c7GQxT3atTXZRz3hbTT-nyCo62JnUBeKlFZJUF
        spreadSheetId: 1hUKBaJBS5CuCi3AKnyCuLrk_RSzEKWHC3AST4FVJCdk
