# Configurações globais
defaults:
  timeZone: America/Sao_Paulo
  runtimeVersion: V8

# Configurações dos projetos
projects:
  salario:
    _debug:
      name: Macros Salários _debug
      scriptId: 1ni6ZUXl1lqfBRik93jEyMI_K7-nWJBGwHPIVAb5Fw-IHZTF1UPfEiBIL
      spreadSheetId: 1n1ypLBl5fPO4eClA9uIWUvlwwYTuu2lHAwQBmaFdSkI
  
  consumo:
    cafeteria:
      _debug:
        name: Macros Cafeteria _debug
        scriptId: 1950SgMmrmWZw6clxlsFZlU6TmBnwRdahBh7entPoVAteqFta_iNNZMy-
        spreadSheetId: 15mSmurGhqrG6o1t4vr2aLPOHN2HJ_Y6SK3od-2v0CbI
    saara:
      _debug:
        name: Macros Saara _debug
        scriptId: 1j2qOwS6Iehduk1IqwckujJmX-nV9AIiOU0yik-f4ja5oIcXHQNnsZMSJ
        spreadSheetId: 1o0SdfBj15wgp4VB3ajwrrChwiU6cq2NEgkBsTjFZAmk
    castelo:
      _debug:
        name: Macros Castelo _debug
        scriptId: 1weezYUwBRbpriYYtaAetmkUdPQcNJUz_Q8G1e3qoZmH5UdRMK5m0c4Yh
        spreadSheetId: 1tCBoBkFnbjwHKiCN6TiLpwO_X9Z0Z7WKd9y7cz_2yIM
    stones:
      _debug:
        name: Macros Stones _debug
        scriptId: 1x-UClZ5PEuUYbwrcM2c7GQxT3atTXZRz3hbTT-nyCo62JnUBeKlFZJUF
        spreadSheetId: 1hUKBaJBS5CuCi3AKnyCuLrk_RSzEKWHC3AST4FVJCdk
