# Configurações globais
defaults:
  timeZone: America/Sao_Paulo
  runtimeVersion: V8

# Configurações dos projetos
projects:
  salario:
    2024:
      name: Macros Salários 2024
      scriptId: 1piXZFH-QithkQm-Q5_S2HVsAZAlURV9iPKvgA_h4icEnNL9cJ0WgtMMJ
      spreadSheetId: 1xE0OSx7V6fc5SoDM6L6kJTuj-F3705tkc6XQe-lJUns
  
  consumo:
    cafeteria:
      2024:
        name: Macros Cafeteria 2024
        scriptId: 11vi0dyEeT43B9Gzprc_FoyqZfKAt_SpmPERsF0MpMG-9tOMWT_YkDa1p
        spreadSheetId: 1DVwbcihxArqQC1xXcZN4RVkdzlco270ikI5tdRY55UI
    saara:
      2024:
        name: Macros Saara 2024
        scriptId: 1hXR1oaQdUJTNgYHS6cWrd1_F5Z-cV7U1I1tz4CHrfatkIFVmzW9N145W
        spreadSheetId: 1FRgOyMG4LmyNcDydBOsd_fpolPHV9VXOkBSHrSx6j4k
    castelo:
      2024:
        name: Macros Castelo 2024
        scriptId: 1JmMj09mr2XZCoL04I5w9Bqkwd9-Vy3YtwRALiy-w7ItHQeC2lxg7PyGP
        spreadSheetId: 1PrfuhwbCdhKN68p-HyYh5anyBWLY3e9FAojzlsRff9U
    stones:
      2024:
        name: Macros Stones 2024
        scriptId: 1nioOhx_pLkusxhjPrchT4S0ToBW93YygTppDWfSZkpbKuZDr22AjRcv9
        spreadSheetId: 1G5_yrB3yKdOak0Ia0jsSVoADi1YDGBkeseIEGvu252Y
